name: EAS Optimized Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  ota_or_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_UPDATE_ACCESS_TOKEN }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set profile and branch variables
        run: |
          if [ "${{ github.ref_name }}" == "staging" ]; then
            echo "PROFILE=staging" >> $GITHUB_ENV
            echo "BRANCH=staging" >> $GITHUB_ENV
          else
            echo "PROFILE=production" >> $GITHUB_ENV
            echo "BRANCH=production" >> $GITHUB_ENV
          fi

      # PUBLICAR APENAS PARA ANDROID E IOS (Ignora Web)
      - name: Publish OTA update
        run: eas update --branch ${{ env.BRANCH }} --platform android --platform ios --non-interactive --message "${{ github.event.head_commit.message }}"

      # BUILD DO APK (Apenas Android)
      - name: Build Android APK
        if: contains(github.event.head_commit.message, '[build]')
        run: eas build --platform android --profile ${{ env.PROFILE }} --non-interactive --no-wait